name: CD

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: reallifedeveloper/github-workflows/.github/workflows/maven-release.yaml@main
    with:
      main-branch: master
    secrets: inherit
    permissions:
      contents: write
